In [1]:
#Import pandas, matplotlib.pyplot, and seaborn in the correct lines below
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
opera = pd.read_csv('/Users/angelique/Documents/GitHub/New_Opera_Company_Capstone/city-level-runs.csv')
opera.head()

index  season iso     city     composer        db        dd nat mf  \
0      0    1213  al   Tirana     Lortzing  18011023  18510121  de  m   
1      1    1213  al   Tirana       Mozart  17560127  17911205  at  m   
2      2    1213  al   Tirana      Puccini  18581222  19241129  it  m   
3      3    1213  am  Yerevan  Spendiaryan  18711020  19280507  am  m   
4      4    1213  am  Yerevan    Tigranian  18791226  19500210  am  m   

                    work worknat type  start date  performances production  
0  Ali Pascha von Janina      de   ~B    20130323             4        NaN  
1           Don Giovanni      it    ~    20130518             3        NaN  
2                  Tosca      it    ~    20130213             2        NaN  
3                 Almast      am    ~    20130711             1        NaN  
4                 Anoush      am    ~    20130511             3        NaN

In [5]:
# Check the length of each entry in the 'db' column
opera['db_length'] = opera['db'].apply(lambda x: len(str(x)))

In [7]:
opera['db_length'].nunique()

5

In [9]:
# Check the length of each entry in the 'dd' column
opera['dd_length'] = opera['dd'].apply(lambda x: len(str(x)))
opera['dd_length'].nunique()

6

In [11]:
opera['db_length'].unique()

array([8, 4, 6, 3, 7])

In [13]:
# Check the length of each entry in the 'start date' column
opera['sd_length'] = opera['start date'].apply(lambda x: len(str(x)))
opera['sd_length'].nunique()

1

In [15]:
# Filter rows where the length of the 'db' column is not 8
opera[opera['db'].apply(lambda x: len(str(x)) != 8)]

index  season iso          city         composer    db    dd nat mf  \
11        11    1213  ar  Buenos Aires      Rakhmaninov  1873  1943  ru  m   
12        12    1213  ar  Buenos Aires      Rakhmaninov  1873  1943  ru  m   
14        14    1213  ar  Buenos Aires        Strauss,R  1864  1949  de  m   
15        15    1213  ar  Buenos Aires    Tchaikovsky,P  1840  1893  ru  m   
19        19    1213  ar      La Plata          Albeniz  1860  1909  es  m   
...      ...     ...  ..           ...              ...   ...   ...  .. ..   
33102  33102    1718  us    Wilmington          Ching,M  1958   NaN  us  m   
33110  33110    1718  uy    Montevideo          Menotti  1911  2007  us  m   
33113  33113    1718  uz      Tashkent        Abdullaev  1947   NaN  uz  m   
33120  33120    1718  uz      Tashkent  Rimsky-Korsakov  1844  1908  ru  m   
33122  33122    1718  uz      Tashkent       Rubinstein  1829  1894  ru  m   

                         work worknat type  start date  performances  \
11                      Aleko      ru   ~B    20130514             4   
12        Francesca da Rimini      ru    ~    20130514             4   
14     Die Frau ohne Schatten      de    ~    20130611             4   
15              Eugene Onegin      ru    ~    20121109             5   
19             Pepita Jimenez      es    ~    20121028             3   
...                       ...     ...  ...         ...           ...   
33102           Buoso's Ghost      us   ~B    20180429             2   
33110              The Consul      us    ~    20170911             3   
33113                 Sadokat      uz    ~    20170921             3   
33120        The Tsar's Bride      ru    ~    20171007             5   
33122               Der Damon      ru    ~    20180408             2   

      production  db_length  dd_length  sd_length  
11           NaN          4          4          8  
12           NaN          4          4          8  
14           NaN          4          4          8  
15             !          4          4          8  
19           NaN          4          4          8  
...          ...        ...        ...        ...  
33102        NaN          4          3          8  
33110          !          4          4          8  
33113        NaN          4          3          8  
33120        NaN          4          4          8  
33122        NaN          4          4          8  

[11402 rows x 18 columns]

In [17]:
# Convert the 'db' and 'dd' column to string, and then extract the first four characters
opera['db'] = opera['db'].astype(str).str[:4]
opera['dd'] = opera['dd'].astype(str).str[:4]

In [19]:
# Check the length of each entry in the 'db' column
opera['db_length'] = opera['db'].apply(lambda x: len(str(x)))

# Check the length of each entry in the 'dd' column
opera['dd_length'] = opera['dd'].apply(lambda x: len(str(x)))

In [21]:
opera['db_length'].nunique()

2

In [23]:
opera['db_length'].unique()

array([4, 3])

In [25]:
# Filter rows where the length of the 'db' column is not 8
opera[opera['db'].apply(lambda x: len(str(x)) != 4)]

index  season iso         city    composer   db   dd nat mf  \
247      247    1213  au    Melbourne       Young  nan  nan  au  m   
1445    1445    1213  de  Gut Immling        Auer  nan  nan  de  m   
1639    1639    1213  de         Kiel    Wilden,B  nan  nan  de  m   
1973    1973    1213  de      Rostock     Russman  nan  nan   ?  m   
2804    2804    1213  hu     Budapest      Javori  nan  nan  hu  m   
...      ...     ...  ..          ...         ...  ...  ...  .. ..   
32984  32984    1718  us      Phoenix  Morganelli  nan  nan   ?  m   
32985  32985    1718  us      Phoenix  Morganelli  nan  nan   ?  m   
32991  32991    1718  us   Pittsburgh        Beck  nan  nan  us  m   
33005  33005    1718  us      Raleigh     Davis,T  nan  nan  us  m   
33064  33064    1718  us      Seattle       Perla  nan  nan  us  m   

                                work worknat type  start date  performances  \
247             The Minotaur Trilogy      au    ~    20121018             5   
1445             Der Brandner Kasper      de    ~    20130712             6   
1639                   Pit und Paula      de   ~C    20130405             6   
1973   Happy Birthday, Mr. President       ?    ~    20130127             8   
2804                   Wedding Dance      hu   ~L    20121006            11   
...                              ...     ...  ...         ...           ...   
32984          Hercules vs. Vampires       ?    ~    20171015             1   
32985          Hercules vs. Vampires       ?    ~    20171021             2   
32991                  The Long Walk      us    ~    20180120             4   
33005   Family Secrets: Kith and Kin      us    ~    20180215             2   
33064              An American Dream      us    ~    20170907             6   

      production  db_length  dd_length  sd_length  
247          NaN          3          3          8  
1445         NaN          3          3          8  
1639           P          3          3          8  
1973           P          3          3          8  
2804         NaN          3          3          8  
...          ...        ...        ...        ...  
32984        NaN          3          3          8  
32985        NaN          3          3          8  
32991        NaN          3          3          8  
33005          P          3          3          8  
33064        NaN          3          3          8  

[169 rows x 18 columns]

In [27]:
import numpy as np

opera['db'] = opera['db'].replace('nan', np.nan)

In [29]:
opera['dd'] = opera['dd'].replace('nan', np.nan)

In [31]:
opera['db_length'].unique()

array([4, 3])

In [33]:
opera['dd_length'].unique()

array([4, 3])

In [35]:
opera.head()

index  season iso     city     composer    db    dd nat mf  \
0      0    1213  al   Tirana     Lortzing  1801  1851  de  m   
1      1    1213  al   Tirana       Mozart  1756  1791  at  m   
2      2    1213  al   Tirana      Puccini  1858  1924  it  m   
3      3    1213  am  Yerevan  Spendiaryan  1871  1928  am  m   
4      4    1213  am  Yerevan    Tigranian  1879  1950  am  m   

                    work worknat type  start date  performances production  \
0  Ali Pascha von Janina      de   ~B    20130323             4        NaN   
1           Don Giovanni      it    ~    20130518             3        NaN   
2                  Tosca      it    ~    20130213             2        NaN   
3                 Almast      am    ~    20130711             1        NaN   
4                 Anoush      am    ~    20130511             3        NaN   

   db_length  dd_length  sd_length  
0          4          4          8  
1          4          4          8  
2          4          4          8  
3          4          4          8  
4          4          4          8

In [37]:
# Convert the 'start date' column to datetime format
opera['start date'] = pd.to_datetime(opera['start date'], format='%Y%m%d')

In [39]:
opera.head()

index  season iso     city     composer    db    dd nat mf  \
0      0    1213  al   Tirana     Lortzing  1801  1851  de  m   
1      1    1213  al   Tirana       Mozart  1756  1791  at  m   
2      2    1213  al   Tirana      Puccini  1858  1924  it  m   
3      3    1213  am  Yerevan  Spendiaryan  1871  1928  am  m   
4      4    1213  am  Yerevan    Tigranian  1879  1950  am  m   

                    work worknat type start date  performances production  \
0  Ali Pascha von Janina      de   ~B 2013-03-23             4        NaN   
1           Don Giovanni      it    ~ 2013-05-18             3        NaN   
2                  Tosca      it    ~ 2013-02-13             2        NaN   
3                 Almast      am    ~ 2013-07-11             1        NaN   
4                 Anoush      am    ~ 2013-05-11             3        NaN   

   db_length  dd_length  sd_length  
0          4          4          8  
1          4          4          8  
2          4          4          8  
3          4          4          8  
4          4          4          8

In [41]:
opera['type'].nunique()

23